name: my_uikit
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: '>=2.18.2 <3.0.0'
dependencies:
  flutter:
    sdk: flutter
  bubble_tab_indicator: ^0.1.6
  cupertino_icons: ^1.0.5
  dio: ^4.0.6
  draggable_fab: ^0.1.4
  dropdown_button2: ^1.8.9
  flick_video_player: ^0.5.0
  floating: ^1.1.1+1
  freezed: ^2.2.1
  freezed_annotation: ^2.2.0
  get: ^4.6.5
  google_fonts: ^3.0.1
  http: ^0.13.5
  json_serializable: ^6.5.4
  readmore: ^2.2.0
  video_player: ^2.4.7
dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.3.2
  flutter_lints: ^2.0.1
flutter:
  uses-material-design: true
